#Actions with server Azure
```{r setting connection}
library(RODBC)    

connectionString <- "Driver={ODBC Driver 13 for SQL Server};Server=tcp:chainreaction.database.windows.net,1433;Database=chainreaction;Uid=hacker@chainreaction;Pwd=kotbumnahpro4$;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"

myconn <- odbcDriverConnect(connectionString)
```

#Pull/push
Не исполнять следующие два чанка (они просто, чтобы не потерять).
Они тянут из сервера и возвращают
```{r saving data to SQL server}
# Save the table to the database
sqlSave(channel=myconn, dat=iris, tablename = "iris")
```

```{r request data from SQL server}
#request data
sqlQuery_m1 <- "SELECT * FROM iris"
m1 <- sqlQuery(myconn, sqlQuery_m1)
```

#Блок про статистику юзера
#Pulling data
```{r}
userid_fromhtml = "34"
users <- sqlQuery(myconn, "SELECT * FROM users3")

transactions <- sqlQuery(myconn, "SELECT * FROM transactions3")

products <- sqlQuery(myconn, "SELECT * FROM products3")
products$description <- as.character(products$description)
products$name <- as.character(products$name)
products <- dplyr::rename(products, "product" = "id")
```

```{r message=FALSE, warning=FALSE}
library(dplyr)
#нашли данные по конкретному юзеру
walletCertain = users[which(users$id == userid_fromhtml),]
walletCertain = walletCertain$wallet

#узнаем, что именно он купил
trCertainUser = dplyr::filter(transactions, as.character(from) == as.character(walletCertain))
trCertainUserPro <- left_join(trCertainUser, products, by = "product")
trCertainUserPro <- trCertainUserPro %>% dplyr::arrange(-time)
if (nrow(trCertainUserPro) > 5){
  trCertainUserPro <- trCertainUserPro[1:5,]
}

trCertainUserPro$name
```

#Recom system
```{r}
library(tidyr)

recData <- left_join(transactions, dplyr::rename(dplyr::select(users, id, wallet), "from" = "wallet"))
recData <- dplyr::select(recData, id, value, product)
recData <- recData %>% group_by(id, product) %>% summarise_all(sum)
recData <- spread(recData, key = product, value = value)

recData <- as.data.frame(recData)
rownames(recData) = recData$id
recData = dplyr::select(recData, -id)

library(recommenderlab)

recData = as.matrix(recData)
r = as(recData, "realRatingMatrix")

r <- binarize(r, minRating = 2)

recc_model <- Recommender(data = r, method = "IBCF", parameter = list(k = 30)) 
```

#Предсказываем
```{r}
recc_predicted <- predict(object = recc_model, newdata = r[2,])

recc_predicted@itemLabels[recc_predicted@items[[1]]]

#узнаём заголовки рекомендованного
products$product <- as.character(products$product)
indexTitle = match(products$product, pred)
indexTitle <- na.omit(indexTitle)
products$name[indexTitle]
```

#demo part
Это создание пробников. Не исполнять. 
```{r}
users <- read.csv("users.csv", sep = ";", stringsAsFactors = F)
sqlSave(channel=myconn, dat=users, tablename = "users3")

transactions <- read.csv("transactions.csv", sep = ";", stringsAsFactors = F)
RODBC::sqlSave(channel=myconn, dat=transactions, tablename = "transactions3", rownames=F)

products <- read.csv("products.csv", sep = ";", stringsAsFactors = F)
sqlUpdate(channel=myconn, dat=products, tablename = "products3")
```




